package models;

import java.math.BigInteger;
import java.sql.Timestamp;
import java.util.Map;

/**
 * This class represents the "BlogHostPosts" schema from the database.
 * @author collin
 *
 */
@Table("BlogHostPosts")
public final class BlogHostPosts extends Model
{
	/**
	 * Primary key. Auto increment from the database.
	 */
	@Column(columnName="id", methodName="setID", methodParameter=BigInteger.class, primaryKey=true, autoGenerated=true)
	private BigInteger id;
	
	@Column(columnName="site_id", methodName="setSiteID", methodParameter=Integer.class)
	private Integer site_id;
	
	@Column(columnName="post_title", methodName="setPostTitle", methodParameter=String.class)
	private String post_title;
	
	@Column(columnName="post_text", methodName="setPostText", methodParameter=String.class)
	private String post_text;
	
	@Column(columnName="picture", methodName="setPicture", methodParameter=byte[].class)
	private byte[] picture;
	
	@Column(columnName="date_posted", methodName="setDatePosted", methodParameter=Timestamp.class)
	private Timestamp date_posted;
	
	@Column(columnName="date_modified", methodName="setDateModified", methodParameter=Timestamp.class)
	private Timestamp date_modified;
	
	/**
	 * Constructor. Creates a brand new BlogHostPosts rows.
	 * @param site_id
	 * @param post_title
	 * @param post_text
	 * @param picture
	 * @param date_posted
	 * @param date_modified
	 */
	public BlogHostPosts(Integer site_id, String post_title,
			String post_text, byte[] picture, Timestamp date_posted,
			Timestamp date_modified)
	{
		resetAutoGenerated();
		setSiteID(site_id);
		setPostTitle(post_title);
		setPostText(post_text);
		setPicture(picture);
		setDatePosted(date_posted);
		setDateModified(date_modified);
	}
	
	/**
	 * Constructor. This constructor is meant to be called when the
	 * parameters come from an existing row in a table of this schema.
	 * @param columnParameters column name to value mappings
	 */
	public BlogHostPosts(Map<String, Object> columnParameters)
	{
		super(columnParameters);
	}
	
	/**
	 * Gets the ID of this row.
	 * @return id
	 */
	public BigInteger getID()
	{
		return id;
	}
	
	/**
	 * Gets the site ID of this row.
	 * @return site_id
	 */
	public Integer getSiteID()
	{
		return site_id;
	}
	
	/**
	 * Gets the post title of this row.
	 * @return post_title
	 */
	public String getPostTitle()
	{
		return post_title;
	}
	
	/**
	 * Gets the post text of this row.
	 * @return post_text
	 */
	public String getPostText()
	{
		return post_text;
	}
	
	/**
	 * Gets the picture of this row.
	 * @return picture
	 */
	public byte[] getPicture()
	{
		return picture;
	}
	
	/**
	 * Gets the date posted of this row.
	 * @return date_posted
	 */
	public Timestamp getDatePosted()
	{
		return date_posted;
	}
	
	/**
	 * Gets the date modified of this row.
	 * @return date_modified
	 */
	public Timestamp getDateModified()
	{
		return date_modified;
	}
	
	/**
	 * Sets the ID of this row.
	 * Use this method with caution as some
	 * database schema ID's are managed automatically.
	 * @param id ID
	 */
	public void setID(BigInteger id)
	{
		if(checkVariable(this.id, id))
		{
			changed = true;
			this.id = id;
		}
	}
	
	/**
	 * Sets the site ID of this row.
	 * @param site_id Site ID
	 */
	public void setSiteID(Integer site_id)
	{
		if(checkVariable(this.site_id, site_id))
		{
			changed = true;
			this.site_id = site_id;
		}
	}
	
	/**
	 * Sets the post title of this row.
	 * @param post_title Post Title
	 */
	public void setPostTitle(String post_title)
	{
		if(checkVariable(this.post_title, post_title))
		{
			changed = true;
			this.post_title = post_title;
		}
	}
	
	/**
	 * Sets the post text of this row.
	 * @param post_text Post Text
	 */
	public void setPostText(String post_text)
	{
		if(checkVariable(this.post_text, post_text))
		{
			changed = true;
			this.post_text = post_text;
		}
	}
	
	/**
	 * Sets the picture of this row.
	 * @param picture Picture
	 */
	public void setPicture(byte[] picture)
	{
		if(checkVariable(this.picture, picture))
		{
			changed = true;
			this.picture = picture;
		}
	}
	
	/**
	 * Sets the date posted of this row.
	 * @param date_posted Date Posted
	 */
	public void setDatePosted(Timestamp date_posted)
	{
		if(checkVariable(this.date_posted, date_posted))
		{
			changed = true;
			this.date_posted = date_posted;
		}
	}
	
	/**
	 * Sets the date modified of this row.
	 * @param date_modified Date Modified
	 */
	public void setDateModified(Timestamp date_modified)
	{
		if(checkVariable(this.date_modified, date_modified))
		{
			changed = true;
			this.date_modified = date_modified;
		}
	}
	
	protected void resetAutoGenerated()
	{
		setID(new BigInteger("-1"));
	}
	
	/**
	 * Checks if the given object is equal to this one.
	 * Two BlogHostPosts are equal if their IDs are equal.
	 * @param other object for comparison
	 * @return true if they are equal, false otherwise
	 */
	@Override
	public boolean equals(Object other)
	{
		if(other instanceof BlogHostPosts)
		{
			return getID().equals(((BlogHostPosts) other).getID());
		}
		
		return false;
	}
}
