package models;

import java.math.BigDecimal;
import java.util.Map;

/**
 * This class represents the "BlogHostStores" schema from the database.
 * @author collin
 *
 */
@Table("BlogHostStores")
final public class BlogHostStores extends Model
{
	/**
	 * Primary key. Auto increment from the database.
	 */
	@Column(columnName="id", methodName="setID", methodParameter=Integer.class, autoGenerated=true, primaryKey=true)
	private Integer id;
	
	@Column(columnName="creator_id", methodName="setCreatorID", methodParameter=Integer.class)
	private Integer creator_id;
	
	@Column(columnName="item_name", methodName="setItemName", methodParameter=String.class)
	private String item_name;
	
	@Column(columnName="item_description", methodName="setItemDescription", methodParameter=String.class)
	private String item_description;
	
	@Column(columnName="picture", methodName="setPicture", methodParameter=byte[].class)
	private byte[] picture;
	
	@Column(columnName="amount", methodName="setAmount", methodParameter=BigDecimal.class)
	private BigDecimal amount;
	
	/**
	 * Constructor. Creates a brand new BlogHostStores row.
	 * @param creator_id
	 * @param item_name
	 * @param item_description
	 * @param picture
	 */
	public BlogHostStores(Integer creator_id, String item_name,
			String item_description, byte[] picture, BigDecimal amount)
	{
		resetAutoGenerated();
		setCreatorID(creator_id);
		setItemName(item_name);
		setItemDescription(item_description);
		setPicture(picture);
		setAmount(amount);
	}
	
	/**
	 * Constructor. This constructor is meant to be called when the
	 * parameters come from an existing row in a table of this schema.
	 * @param columnParameters column name to value mappings
	 */
	public BlogHostStores(Map<String, Object> columnParameters)
	{
		super(columnParameters);
	}

	/**
	 * Gets the ID of this row.
	 * @return id
	 */
	public Integer getID()
	{
		return id;
	}

	/**
	 * Gets the creator ID of this row.
	 * @return creator_id
	 */
	public Integer getCreatorID()
	{
		return creator_id;
	}

	/**
	 * Gets the item name of this row.
	 * @return item_name
	 */
	public String getItemName()
	{
		return item_name;
	}

	/**
	 * Gets the item description of this row.
	 * @return item_description
	 */
	public String getItemDescription()
	{
		return item_description;
	}

	/**
	 * Gets the picture of this row.
	 * @return picture
	 */
	public byte[] getPicture()
	{
		return picture;
	}
	
	/**
	 * Gets the amount of this row.
	 * @return amount
	 */
	public BigDecimal getAmount()
	{
		return amount;
	}

	/**
	 * Sets the ID of this row.
	 * Use this method with caution as some
	 * database schema ID's are managed
	 * automatically.
	 * @param id ID
	 */
	public void setID(Integer id)
	{
		if(checkVariable(this.id, id))
		{
			changed = true;
			this.id = id;
		}
	}

	/**
	 * Sets the creator ID of this row.
	 * @param creator_id Creator ID
	 */
	public void setCreatorID(Integer creator_id)
	{
		if(checkVariable(this.creator_id, creator_id))
		{
			changed = true;
			this.creator_id = creator_id;
		}
	}

	/**
	 * Sets the item name of this row.
	 * @param item_name Item Name
	 */
	public void setItemName(String item_name)
	{
		if(checkVariable(this.item_name, item_name))
		{
			changed = true;
			this.item_name = item_name;
		}
	}

	/**
	 * Sets the item description of this row.
	 * @param item_description Item Description
	 */
	public void setItemDescription(String item_description)
	{
		if(checkVariable(this.item_description, item_description))
		{
			changed = true;
			this.item_description = item_description;
		}
	}

	/**
	 * Sets the picture of this row.
	 * @param picture Picture
	 */
	public void setPicture(byte[] picture)
	{
		if(checkVariable(this.picture, picture))
		{
			changed = true;
			this.picture = picture;
		}
	}
	
	/**
	 * Sets the amount of this row.
	 * @param amount Amount
	 */
	public void setAmount(BigDecimal amount)
	{
		if(checkVariable(this.amount, amount))
		{
			changed = true;
			this.amount = amount;
		}
	}
	
	protected void resetAutoGenerated()
	{
		setID(-1);
	}
	
	/**
	 * Checks if the given object is equal to this one.
	 * Two BlogHostStores are equal if their IDs are equal.
	 * @param other object for comparison
	 * @return true if they are equal, false otherwise
	 */
	@Override
	public boolean equals(Object other)
	{
		if(other instanceof BlogHostStores)
		{
			return getID().equals(((BlogHostStores) other).getID());
		}
		
		return false;
	}
}
