package models;

import java.util.Map;

/**
 * This class represents the "BlogHostCreators" schema from the database.
 * @author collin
 *
 */
@Table("BlogHostCreators")
final public class BlogHostCreators extends Model
{
	/**
	 * Primary key. Auto increment from the database.
	 */
	@Column(columnName="id", methodName="setID", methodParameter=Integer.class, autoGenerated=true, primaryKey=true)
	private Integer id;
	
	@Column(length=50, columnName="user_name", methodName="setUserName", methodParameter=String.class)
	private String user_name;
	
	@Column(length=50, columnName="first_name", methodName="setFirstName", methodParameter=String.class)
	private String first_name;
	
	@Column(length=50, columnName="last_name", methodName="setLastName", methodParameter=String.class)
	private String last_name;
	
	@Column(length=50, columnName="email", methodName="setEmail", methodParameter=String.class)
	private String email;
	
	@Column(columnName="age", methodName="setAge", methodParameter=Integer.class)
	private Integer age;
	
	@Column(length=50, columnName="password", methodName="setPassword", methodParameter=String.class)
	private String password;
	
	@Column(columnName="profile_picture", methodName="setProfilePicture", methodParameter=byte[].class)
	private byte[] profile_picture;
	
	@Column(columnName="admin", methodName="setAdmin", methodParameter=Boolean.class)
	private Boolean admin;
	
	/**
	 * Constructor. Creates a brand new BlogHostCreators row.
	 * @param user_name
	 * @param first_name
	 * @param last_name
	 * @param age
	 * @param password
	 * @param profile_picture
	 * @param admin
	 */
	public BlogHostCreators(String user_name, String first_name,
			String last_name, String email, Integer age, String password, byte[] profile_picture,
			Boolean admin)
	{
		resetAutoGenerated();
		setUserName(user_name);
		setFirstName(first_name);
		setLastName(last_name);
		setEmail(email);
		setAge(age);
		setPassword(password);
		setProfilePicture(profile_picture);
		setAdmin(admin);
	}
	
	/**
	 * Constructor. This constructor is meant to be called when the
	 * parameters come from an existing row in a table of this schema.
	 * @param columnParameters column name to value mappings
	 */
	public BlogHostCreators(Map<String, Object> columnParameters)
	{
		super(columnParameters);
	}
	
	/**
	 * Gets the ID of this row.
	 * @return id
	 */
	public Integer getID()
	{
		return id;
	}
	
	/**
	 * Gets the user name of this row.
	 * @return user_name
	 */
	public String getUserName()
	{
		return user_name;
	}
	
	/**
	 * Gets the first name of this row.
	 * @return first_name
	 */
	public String getFirstName()
	{
		return first_name;
	}
	
	/**
	 * Gets the last name of this row.
	 * @return last_name
	 */
	public String getLastName()
	{
		return last_name;
	}
	
	/**
	 * Gets the email of this row.
	 * @return email
	 */
	public String getEmail()
	{
		return email;
	}
	
	/**
	 * Gets the age of this row.
	 * @return age
	 */
	public Integer getAge()
	{
		return age;
	}
	
	/**
	 * Gets the password of this row.
	 * @return password
	 */
	public String getPassword()
	{
		return password;
	}
	
	/**
	 * Gets the profile picture of this row.
	 * @return profile_picture
	 */
	public byte[] getProfilePicture()
	{
		return profile_picture;
	}
	
	/**
	 * Gets the admin of this row.
	 * @return admin
	 */
	public Boolean getAdmin()
	{
		return admin;
	}
	
	/**
	 * Sets the ID of this row.
	 * Use this method with caution as some
	 * database schema ID's are managed
	 * automatically.
	 * @param id ID
	 */
	public void setID(Integer id)
	{
		if(checkVariable(this.id, id))
		{
			changed = true;
			this.id = id;
		}
	}
	
	/**
	 * Sets the user name of this row.
	 * @param user_name User Name
	 */
	public void setUserName(String user_name)
	{
		if(checkVariable(this.user_name, user_name))
		{
			changed = true;
			this.user_name = user_name;
		}
	}
	
	/**
	 * Sets the first name of this row.
	 * @param first_name First Name
	 */
	public void setFirstName(String first_name)
	{
		if(checkVariable(this.first_name, first_name))
		{
			changed = true;
			this.first_name = first_name;
		}
	}
	
	/**
	 * Sets the last name of this row.
	 * @param last_name Last Name
	 */
	public void setLastName(String last_name)
	{
		if(checkVariable(this.last_name, last_name))
		{
			changed = true;
			this.last_name = last_name;
		}
	}
	
	/**
	 * Sets the email of this row.
	 * @param email Email
	 */
	public void setEmail(String email)
	{
		if(checkVariable(this.email, email))
		{
			changed = true;
			this.email = email;
		}
	}
	
	/**
	 * Sets the age of this row.
	 * @param age Age
	 */
	public void setAge(Integer age)
	{
		if(checkVariable(this.age, age))
		{
			changed = true;
			this.age = age;
		}
	}
	
	/**
	 * Sets the password of this row.
	 * @param password Password
	 */
	public void setPassword(String password)
	{
		if(checkVariable(this.password, password))
		{
			changed = true;
			this.password = password;
		}
	}
	
	/**
	 * Sets the profile picture of this row.
	 * @param profile_picture Profile Picture
	 */
	public void setProfilePicture(byte[] profile_picture)
	{
		if(checkVariable(this.profile_picture, profile_picture))
		{
			changed = true;
			this.profile_picture = profile_picture;
		}
	}
	
	/**
	 * Sets the admin of this row.
	 * @param admin Admin
	 */
	public void setAdmin(Boolean admin)
	{
		if(checkVariable(this.admin, admin))
		{
			changed = true;
			this.admin = admin;
		}
	}
	
	protected void resetAutoGenerated()
	{
		setID(-1);
	}
	
	/**
	 * Checks if the given object is equal to this one.
	 * Two BlogHostCreators are equal if their IDs are equal.
	 * @param other object for comparison
	 * @return true if they are equal, false otherwise
	 */
	@Override
	public boolean equals(Object other)
	{
		if(other instanceof BlogHostCreators)
		{
			return getID().equals(((BlogHostCreators) other).getID());
		}
		
		return false;
	}
}
