package models;

import java.util.Map;

/**
 * This class represents the "BlogHostMods" schema from the database.
 * @author collin
 *
 */
@Table("BlogHostMods")
public final class BlogHostMods extends Model
{
	@Column(columnName="mod_id", methodName="setModID", methodParameter=Integer.class, primaryKey=true)
	private Integer mod_id;
	
	@Column(columnName="creator_id", methodName="setCreatorID", methodParameter=Integer.class)
	private Integer creator_id;
	
	/**
	 * Constructor. Creates a brand new BlogHostMods row.
	 * @param mod_id
	 * @param creator_id
	 */
	public BlogHostMods(Integer mod_id, Integer creator_id)
	{
		setModID(mod_id);
		setCreatorID(creator_id);
	}
	
	/**
	 * Constructor. This constructor is meant to be called when the
	 * parameters come from an existing row in a table of this schema.
	 * @param columnParameters column name to value mappings
	 */
	public BlogHostMods(Map<String, Object> columnParameters)
	{
		super(columnParameters);
	}
	
	/**
	 * Gets the mod ID of this row.
	 * @return mod_id
	 */
	public Integer getModID()
	{
		return mod_id;
	}
	
	/**
	 * Gets the creator ID of this row.
	 * @return creator_id
	 */
	public Integer getCreatorID()
	{
		return creator_id;
	}
	
	/**
	 * Sets the mod ID of this row.
	 * @param mod_id Mod ID
	 */
	public void setModID(Integer mod_id)
	{
		if(checkVariable(this.mod_id, mod_id))
		{
			changed = true;
			this.mod_id = mod_id;
		}
	}
	
	/**
	 * Sets the creator ID of this row.
	 * @param creator_id Creator ID
	 */
	public void setCreatorID(Integer creator_id)
	{
		if(checkVariable(this.creator_id, creator_id))
		{
			changed = true;
			this.creator_id = creator_id;	
		}
	}
	
	protected void resetAutoGenerated()
	{
		
	}
	
	/**
	 * Checks if the given object is equal to this one.
	 * Two BlogHostComments are equal if their IDs are equal.
	 * @param other object for comparison
	 * @return true if they are equal, false otherwise
	 */
	@Override
	public boolean equals(Object other)
	{
		if(other instanceof BlogHostMods)
		{
			return getModID().equals(((BlogHostMods) other).getModID()) &&
				   getCreatorID().equals(((BlogHostMods) other).getCreatorID());
		}
		
		return false;
	}
}
