package models;

import java.util.Map;

/**
 * This class represents the "BlogHostSites" schema from the database.
 * @author collin
 *
 */
@Table("BlogHostSites")
public final class BlogHostSites extends Model
{
	/**
	 * Primary key. Auto increment from the database.
	 */
	@Column(columnName="id", methodName="setID", methodParameter=Integer.class, autoGenerated=true, primaryKey=true)
	private Integer id;
	
	@Column(columnName="creator_id", methodName="setCreatorID", methodParameter=Integer.class)
	private Integer creator_id;
	
	@Column(columnName="site_url", methodName="setSiteURL", methodParameter=String.class)
	private String site_url;
	
	@Column(columnName="site_name", methodName="setSiteName", methodParameter=String.class)
	private String site_name;
	
	@Column(columnName="custom_html", methodName="setCustomHTML", methodParameter=String.class)
	private String custom_html;
	
	/**
	 * Constructor. Creates a brand new BlogHostSites row.
	 * @param creator_id
	 * @param site_url
	 * @param site_name
	 * @param custom_html
	 */
	public BlogHostSites(Integer creator_id, String site_url,
			String site_name, String custom_html)
	{
		resetAutoGenerated();
		setCreatorID(creator_id);
		setSiteURL(site_url);
		setSiteName(site_name);
		setCustomHTML(custom_html);
	}
	
	/**
	 * Constructor. This constructor is meant to be called when the
	 * parameters come from an existing row in a table of this schema.
	 * @param columnParameters column name to value mappings
	 */
	public BlogHostSites(Map<String, Object> columnParameters)
	{
		super(columnParameters);
	}
	
	/**
	 * Gets the ID of this row.
	 * @return id
	 */
	public Integer getID()
	{
		return id;
	}
	
	/**
	 * Gets the creator ID of this row.
	 * @return creator_id
	 */
	public Integer getCreatorID()
	{
		return creator_id;
	}
	
	/**
	 * Gets the site URL of this row.
	 * @return site_url
	 */
	public String getSiteURL()
	{
		return site_url;
	}
	
	/**
	 * Gets the site name of this row.
	 * @return site_name
	 */
	public String getSiteName()
	{
		return site_name;
	}
	
	/**
	 * Gets the custom HTML of this row.
	 * @return custom_html
	 */
	public String getCustomHTML()
	{
		return custom_html;
	}
	
	/**
	 * Sets the ID of this row.
	 * Use this method with caution as some
	 * database schema ID's are managed
	 * automatically.
	 * @param id ID
	 */
	public void setID(Integer id)
	{
		this.id = id;
	}
	
	/**
	 * Sets the creator ID of this row.
	 * @param creator_id Creator ID
	 */
	public void setCreatorID(Integer creator_id)
	{
		if(checkVariable(this.creator_id, creator_id))
		{
			changed = true;
			this.creator_id = creator_id;
		}
	}
	
	/**
	 * Sets the site URL of this row.
	 * @param site_url Site URL
	 */
	public void setSiteURL(String site_url)
	{
		if(checkVariable(this.site_url, site_url))
		{
			changed = true;
			this.site_url = site_url;
		}
	}
	
	/**
	 * Sets the site name of this row.
	 * @param site_name Site Name
	 */
	public void setSiteName(String site_name)
	{
		if(checkVariable(this.site_name, site_name))
		{
			changed = true;
			this.site_name = site_name;
		}
	}
	
	/**
	 * Sets the custom HTML of this row.
	 * @param custom_html Custom HTML
	 */
	public void setCustomHTML(String custom_html)
	{
		if(checkVariable(this.custom_html, custom_html))
		{
			changed = true;
			this.custom_html = custom_html;
		}
	}
	
	protected void resetAutoGenerated()
	{
		setID(-1);
	}
	
	/**
	 * Checks if the given object is equal to this one.
	 * Two BlogHostSites are equal if their IDs are equal.
	 * @param other object for comparison
	 * @return true if they are equal, false otherwise
	 */
	@Override
	public boolean equals(Object other)
	{
		if(other instanceof BlogHostSites)
		{
			return getID().equals(((BlogHostSites) other).getID());
		}
		
		return false;
	}
}
