package models;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.FIELD)
public @interface Column
{
	int length() default Integer.MAX_VALUE;
	String columnName();
	String methodName();
	Class<?> methodParameter();
	boolean autoGenerated() default false;
	boolean primaryKey() default false;
}
